version: '2'
services:

  report:
    container_name: report
    command:
      "--spring.profiles.active=docker"
    build:
      context: Report
    image: report:latest
    ports:
      - "8080:8080"
    depends_on:
      patient:
        condition: service_started
      note:
        condition: service_started
    networks:
      - mediscreen-network

  note:
    container_name: note
    build:
      context: Notes
    image: note:latest
    ports:
      - "8082:8082"
    networks:
      - mediscreen-network

  patient:
    container_name: patient
    build:
      context: Patients
    image: patient:latest
    ports:
      - "8081:8081"
    networks:
      - mediscreen-network

networks:
  mediscreen-network:
    driver: bridge