version: '3'
services:

  mysqldb:
    build:
      context: mysqldb
    container_name: mediscreen_mysqldb
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    ports:
      - "3306:3306"
    volumes:
      - mediscreen_mysqldb_data_container:/var/lib/mysql
    networks:
      - mediscreen-network

  mongodb:
    build:
      context: mongodb
    container_name: mediscreen_mongodb
    ports:
      - 27017:27017
    volumes:
      - mediscreen_mongodb_data_container:/data/db
    environment:
      MONGO_INITDB_DATABASE: mediscreen
    networks:
      - mediscreen-network

  angular:
    container_name: mediscreen_angular
    build:
      context: mediscreen-front-angular
    image: angular_mediscreen:latest
    ports:
      - "4200:4200"

  report:
    container_name: mediscreen_report
    command:
      "--spring.profiles.active=docker"
    build:
      context: Report
    image: report:latest
    ports:
      - "8080:8080"
    depends_on:
      patient:
        condition: service_started
      note:
        condition: service_started
    networks:
      - mediscreen-network

  note:
    container_name: mediscreen_note
    command:
      "--spring.profiles.active=docker"
    build:
      context: Notes
    image: note:latest
    ports:
      - "8082:8082"
    depends_on:
      mongodb:
        condition: service_started
    networks:
      - mediscreen-network

  patient:
    container_name: mediscreen_patient
    command:
      "--spring.profiles.active=docker"
    build:
      context: Patients
    image: patient:latest
    ports:
      - "8081:8081"
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - mediscreen-network

volumes:
  mediscreen_mysqldb_data_container:
  mediscreen_mongodb_data_container:

networks:
  mediscreen-network:
    driver: bridge