version: '3'
services:

  mysqldb:
    image: mysql:8
    container_name: mysqldb
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
    networks:
      - mediscreen-network

  mongodb:
    image: mongo:5
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - /data/db
    networks:
      - mediscreen-network

  report:
    container_name: report
    command:
      "--spring.profiles.active=docker"
    build:
      context: Report
    image: report:latest
    ports:
      - "8080:8080"
    depends_on:
      patient:
        condition: service_started
      note:
        condition: service_started
    networks:
      - mediscreen-network

  note:
    container_name: note
    command:
      "--spring.profiles.active=docker"
    build:
      context: Notes
    image: note:latest
    ports:
      - "8082:8082"
    depends_on:
      mongodb:
        condition: service_started
    networks:
      - mediscreen-network

  patient:
    container_name: patient
    command:
      "--spring.profiles.active=docker"
    build:
      context: Patients
    image: patient:latest
    ports:
      - "8081:8081"
    depends_on:
      mysqldb:
        condition: service_started
    networks:
      - mediscreen-network

networks:
  mediscreen-network:
    driver: bridge